### ISSUE TITLE
Unable to Switch Theme in Dark Mode

### ISSUE THREAD

**Issue by qazzym** [notaapp/talk#294] opened 2022-08-19 01:01 UTC
There seems to be a bug where it doesn't seem possible to switch theme while I am using Nota dark mode and macOS is in dark mode as well. But with macOS in light mode I able to switch between Nota light and dark mode easily using the command palette.

**Comment by astoilkov** [comment] 2022-08-19 06:45
Hmm. I can't replicate this.

Are the theme items in the command palette grayed out?

**Comment by qazzym** [comment] 2022-08-19 15:18
Interesting. Yes, they’re grayed out. I’ll try and experiment more.

**Comment by astoilkov** [comment] 2022-08-20 07:22
No need. I found the cause of the problem. The next release will include the fix.

**Comment by astoilkov** [comment] 2023-04-18 06:47
The fix is part of the latest release.

Closing this issue.

**Closed by astoilkov** 2023-04-18 06:47 UTC
Labels: bug, resolved in future release
