### ISSUE TITLE
Workspace actions ineffective

### ISSUE THREAD

**Issue by petrbouchal** [notaapp/talk#388] opened 2023-04-07 14:59 UTC
Unless I am missing something, most workspace-related actions have no effect:
- currently, I see only `root` in the leftmost sidebar (I have no directories inside the root location)
- When I run the `Switch workspace` action (either through palette, menu, right-click on sidebar):
  - I see a list of workspaces I had previously added
  - I can remove these using the `x`
  - but: when I select one and click/hit enter, nothing happens
- When I run `Open` and select a directory, I see an alert "Please note that edits are auto-saved.", but then nothing happens (nothing opens, no change in leftmost sidebar)
- Likewise, dragging a directory onto the editor produces the auto-save alert but nothing after that

This is Nota Version 0.40.4 (Apple Silicon) running on MacOS 13.4 beta (the beta might be the cause?)

**Comment by astoilkov** [comment] 2023-04-08 10:37
Hmm, very strange. In our reporting, there is an error from exactly 19 hours ago (when you wrote the issue). Our reporting is anonymous but it's probably you as this is the only 

From what I see as the reason it's probably caused by corruption in the state of the app. You can go to `~/Library/Application Support/Nota` and rename the `state.json` file. This will clear the state and should fix the problem.

Let me know what happens.

I will also investigate further to ensure this doesn't happen again and the user experience is better (an error is shown instead of nothing happening).

**Comment by petrbouchal** [comment] 2023-04-08 17:44
Thanks for the prompt response. Yes, that was it - I removed state.json and the issue is resolved, all the steps I described now work as expected.

Somewhat surprisingly, this also reset all preferences - would it make sense to store these in a separate file? (On my end, I resolved this by copying the config object from the old state.json file, so no problem here.)

**Comment by petrbouchal** [comment] 2023-04-08 18:17
(If this was just something peculiar going haywire on my machine, I wonder if it's worth any further treatment...)

**Comment by astoilkov** [comment] 2023-04-10 05:50
Great, I'm happy the issue is resolved.

Yes, preferences are part of the state. Actually, everything that's not workspace related is inside that state.json. We can split the state.json file, but it's hard to determine what parts to separate. Splitting also increases the complexity of the code.

I think the best solution is to fix the problem which I plan to do.

I will close this because it doesn't describe well the underlying issue. However, I will work on the problem soon.

**Closed by astoilkov** 2023-04-10 05:50 UTC
