### ISSUE TITLE
Battery impact on m1 mac

### ISSUE THREAD

**Issue by work-leonid** [notaapp/talk#195] opened 2022-04-21 06:26 UTC
Hi! I wanted to know why nota is so energy inefficient. 
Macbook air m1, 2020. Mac OS Monterey 12.3

<img width="876" alt="image" src="https://user-images.githubusercontent.com/8654430/164387393-ecd75f22-ba92-404e-beb2-912396f09047.png">
<img width="350" alt="image" src="https://user-images.githubusercontent.com/8654430/164387428-e57ccd87-07c7-48af-bd27-3618f4e83c42.png">

In comparison, Obsidian
<img width="864" alt="image" src="https://user-images.githubusercontent.com/8654430/164387578-a0b3fb12-8176-443e-8775-6b3403f48dcd.png">

**Comment by astoilkov** [comment] 2022-04-21 10:06
Hi! This seems like a bug. We don't experience the same thing. We've actually done some energy optimizations in the latest release and I think it's possible we missed something.

It's probably caused by something specific to your workspace. I've already started investigating possible causes but in the meantime, if you have time, can you give us a little more information:
- Is the 12 hr average from the latest 0.35 release or it's 6 hours from 0.34 and 6 hours from 0.35 for example?
- Do you have Git enabled in your workspace?
- How many files and folders do you have in your workspace?
- How does Nota compare to other apps? Is the 42,72 value puts it above all other apps?
- What macOS version are you using?
- Is it possible you run `stat -f%z ~/Library/Application\ Support/Nota/state.json` command in the Terminal? It will say how big your Nota state is (we've seen issues with this previously).

I'm sorry for so many questions but such context-specific issues are hard to find.

**Comment by astoilkov** [comment] 2022-04-21 11:42
I think I found the problem. We will improve on this immediately.

I'm still interested in your questions but if you don't have the time we can wait for the next update to see if the issue goes away and then revisit them.

Thanks for reporting!

**Comment by work-leonid** [comment] 2022-04-21 13:59
_Is the 12 hr average from the latest 0.35 release or it's 6 hours from 0.34 and 6 hours from 0.35 for example?_
I had not installed nota before. 

_Do you have Git enabled in your workspace?_
Yes

_How many files and folders do you have in your workspace?_
>1800 files, 9 folders. Almost all files in root folder. 
I checked on an empty folder - the battery number did not change

_How does Nota compare to other apps? Is the 42,72 value puts it above all other apps?_
Far above than other apps

_What macOS version are you using?_
macOS Monterey 12.3 (21E230)

_Is it possible you run stat -f%z ~/Library/Application\ Support/Nota/state.json command in the Terminal? It will say how big your Nota state is (we've seen issues with this previously)._
4330

**Comment by work-leonid** [comment] 2022-04-21 13:59
> I think I found the problem. We will improve on this immediately.
> 
> I'm still interested in your questions but if you don't have the time we can wait for the next update to see if the issue goes away and then revisit them.
> 
> Thanks for reporting!

Thank you! That was fast!

**Comment by astoilkov** [comment] 2022-04-25 11:54
We just released a new update that includes the fix for this. I will close the issue but let me know if you experience any issues.

**Closed by astoilkov** 2022-04-25 11:54 UTC
Labels: bug, resolved in future release
